### PR TITLE
beta RC

### PR DESCRIPTION
**Pull request by ghost**
add exclusions by mechdef or mech tag
add targeted and triggered build to specify what variant
renamed 'pieces' to 'parts' universally to match game language
expose some settings to mod.json

### CODE REVIEW

**Comment by mpstark** [comment]
I've taken a look at things in the diff, a couple style notes that I've noticed:

* Newlines should be at the bottom of all files
* Only use the comment version of ignoring resharper warnings
* Patches all should be in a file named for the class that they are patching

I'll get a better idea when I get it loaded normally

**Comment by ghost** [comment]
Cool.  I'm not sure about point 2, no prob once I get it.  I'm using Rider which has Resharper integrated, I think.  All the exclusions I've seen have been comments.

If make another commit, does it update the PR?  
Thanks!

**Comment by mpstark** [comment]
Yes, just use the branch that is for the PR.

**Comment by ghost** [comment]
I've just pushed an update, hopefully better.

**Pull request closed without merging**
